# Business Objective
#### We have MNIST dataset and by using PyTorch we have to analyze data.

# Import Libraries

In [1]:
import os
import sys
import warnings
import torch


import matplotlib.pyplot as plt
import seaborn as sns

import pandas as pd
import numpy as np


import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader,Dataset
from torchvision import datasets,transforms


%matplotlib inline
warnings.filterwarnings("ignore")    

# Load Data

In [2]:
import torchvision.transforms as transforms
from torchvision.datasets import MNIST
from torch.utils.data import DataLoader

# Define a transform to normalize the data
transform = transforms.ToTensor()

# Download the MNIST training dataset
train_dataset = MNIST(root='./Projects', train=True, transform=transform, download=True)

# Download the MNIST testing dataset
test_dataset = MNIST(root='./Projects', train=False, transform=transform, download=True)

In [3]:
train_dataset

Dataset MNIST
    Number of datapoints: 60000
    Root location: ./Projects
    Split: Train
    StandardTransform
Transform: ToTensor()

In [4]:
test_dataset

Dataset MNIST
    Number of datapoints: 10000
    Root location: ./Projects
    Split: Test
    StandardTransform
Transform: ToTensor()

In [5]:
train_loader = DataLoader(train_dataset, batch_size=10, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=10, shuffle=False)

In [6]:
# 1 --> COLOR CHANNEL, 6 ---> FILTERS(OUTPUT CHANNEL), 3*3 ----> KERNEL , 1 ---> STRIDE
conv1 = nn.Conv2d(1,6,3,1)
# 6 ---> INPUT FITERS OF CONV1, 16 ---> FILTERS, 3*3 --> KERNELS, 1 --> STRIDE
conv2 = nn.Conv2d(6,16,3,1)

In [7]:
for i,(X_train,y_train) in enumerate(train_dataset):
    break

In [8]:
X_train

tensor([[[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,

In [9]:
X_train.shape

torch.Size([1, 28, 28])

In [10]:
x = X_train.view(1,1,28,28)
x

tensor([[[[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 

In [11]:
x = F.relu(conv1(x))
x.shape

torch.Size([1, 6, 26, 26])

In [12]:
x = F.max_pool2d(x,2,2)
x.shape

torch.Size([1, 6, 13, 13])

In [13]:
x = F.relu(conv2(x))
x.shape

torch.Size([1, 16, 11, 11])

In [14]:
x = F.max_pool2d(x,2,2)
x.shape

torch.Size([1, 16, 5, 5])

In [15]:
x.shape

torch.Size([1, 16, 5, 5])

In [16]:
x.view(-1,16*5*5).shape

torch.Size([1, 400])

# Model Building

In [17]:
class ConvNetwork(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = nn.Conv2d(1,6,3,1)
        self.conv2 = nn.Conv2d(6,16,3,1)
        self.fc1 = nn.Linear(5*5*16,120)
        self.fc2 = nn.Linear(120,84)
        self.fc3 = nn.Linear(84,10)
    def forward(self,X):
        X = F.relu(self.conv1(X))
        X = F.max_pool2d(X,2,2)
        X = F.relu(self.conv2(X))
        X = F.max_pool2d(X,2,2)
        X = X.view(-1,16*5*5)
        X = F.relu(self.fc1(X))
        X = F.relu(self.fc2(X))
        X = self.fc3(X)
        return F.log_softmax(X,dim=1)

In [18]:
torch.manual_seed(42)
model = ConvNetwork()
model

ConvNetwork(
  (conv1): Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(3, 3), stride=(1, 1))
  (fc1): Linear(in_features=400, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)

### Total Number of parameters in Model

In [19]:
for param in model.parameters():
    print(param.numel())

54
6
864
16
48000
120
10080
84
840
10


In [20]:
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(),lr = 0.001)

# Training Model

In [21]:
import time
start_time = time.time()




# VARIABLES(TRACKERS)
epochs = 5
train_losses = []
test_losses = []
train_correct = []
test_correct = []


# FOR LOOP
for i in range(epochs):
    trn_corr = 0
    tst_corr = 0




     # TRAIN
    for b, (X_train,y_train) in enumerate(train_loader):
        b+=1
        y_pred = model(X_train)
        loss = criterion(y_pred , y_train)
        
        predicted = torch.max(y_pred.data,1)[1]
        batch_corr = (predicted==y_train).sum()
        trn_corr += batch_corr
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        
        if b%600 == 0:
            print(f"EPOCH: {i} BATCH: {b} LOSS: {loss.item()} ")
            
    train_losses.append(loss)
    train_correct.append(trn_corr)
    
    
    
    # TEST
    with torch.no_grad():
        for b,(X_test,y_test) in enumerate(test_loader):
            y_val = model(X_test)
            predicted = torch.max(y_val.data,1)[1]
            tst_corr += (predicted==y_test).sum()
            
    loss = criterion(y_val,y_test)
    test_losses.append(loss)
    test_correct.append(tst_corr)

    
current_time = time.time()
total = current_time - start_time
print(f"Training took {total/60}minutes")

EPOCH: 0 BATCH: 600 LOSS: 0.042550548911094666 
EPOCH: 0 BATCH: 1200 LOSS: 0.07605952024459839 
EPOCH: 0 BATCH: 1800 LOSS: 0.30995577573776245 
EPOCH: 0 BATCH: 2400 LOSS: 0.02016785740852356 
EPOCH: 0 BATCH: 3000 LOSS: 0.007437355816364288 
EPOCH: 0 BATCH: 3600 LOSS: 0.0012245547259226441 
EPOCH: 0 BATCH: 4200 LOSS: 0.5557299852371216 
EPOCH: 0 BATCH: 4800 LOSS: 0.0668177530169487 
EPOCH: 0 BATCH: 5400 LOSS: 0.007983753457665443 
EPOCH: 0 BATCH: 6000 LOSS: 0.0668204054236412 
EPOCH: 1 BATCH: 600 LOSS: 0.029031146317720413 
EPOCH: 1 BATCH: 1200 LOSS: 0.05128370597958565 
EPOCH: 1 BATCH: 1800 LOSS: 0.0013509824639186263 
EPOCH: 1 BATCH: 2400 LOSS: 0.01731514371931553 
EPOCH: 1 BATCH: 3000 LOSS: 0.2662854492664337 
EPOCH: 1 BATCH: 3600 LOSS: 0.00023901737586129457 
EPOCH: 1 BATCH: 4200 LOSS: 0.0006059271981939673 
EPOCH: 1 BATCH: 4800 LOSS: 0.0006372936186380684 
EPOCH: 1 BATCH: 5400 LOSS: 0.0007654715445823967 
EPOCH: 1 BATCH: 6000 LOSS: 0.06921999901533127 
EPOCH: 2 BATCH: 600 LOSS: 0.0

# Model Evaluation

In [22]:
test_load_all = DataLoader(test_dataset, batch_size=10000,shuffle=False)

In [23]:
with torch.no_grad():
  correct = 0

  for X_test,y_test in test_load_all:
    y_val = model(X_test)
    predicted = torch.max(y_val,1)[1]
    correct += (predicted==y_test).sum()

In [24]:
correct

tensor(9878)

In [25]:
correct.item()

9878

In [26]:
 100*correct.item()/len(test_dataset)

98.78

In [27]:
from sklearn.metrics import confusion_matrix, classification_report

In [29]:
np.set_printoptions(formatter=dict(int= lambda x: f"{x:4}"))
print(np.arange(10).reshape(1,10))
print()

print(confusion_matrix(predicted.view(-1), y_test.view(-1)))

[[   0    1    2    3    4    5    6    7    8    9]]

[[ 972    0    1    0    0    3    6    1    5    0]
 [   0 1131    0    0    0    0    1    3    0    1]
 [   3    1 1027    2    1    0    1    8    3    0]
 [   0    1    0 1003    0   13    0    1    3    0]
 [   0    0    1    0  974    0    2    4    2    5]
 [   0    0    0    2    0  870    2    0    0    4]
 [   4    2    0    0    1    3  944    0    1    0]
 [   1    0    2    2    0    0    0 1008    1    4]
 [   0    0    1    1    1    1    2    2  956    2]
 [   0    0    0    0    5    2    0    1    3  993]]


In [30]:
print(classification_report(predicted.view(-1), y_test.view(-1)))

              precision    recall  f1-score   support

           0       0.99      0.98      0.99       988
           1       1.00      1.00      1.00      1136
           2       1.00      0.98      0.99      1046
           3       0.99      0.98      0.99      1021
           4       0.99      0.99      0.99       988
           5       0.98      0.99      0.98       878
           6       0.99      0.99      0.99       955
           7       0.98      0.99      0.99      1018
           8       0.98      0.99      0.99       966
           9       0.98      0.99      0.99      1004

    accuracy                           0.99     10000
   macro avg       0.99      0.99      0.99     10000
weighted avg       0.99      0.99      0.99     10000



# Conclusion:
#### From above analysis it is clear that we have 99% accuracy by CNN.