In [1]:
import pandas as pd 

In [2]:
import numpy as np 

In [3]:
import matplotlib.pyplot as plt 

In [4]:

import seaborn as sns 

In [5]:
import torch

In [6]:
print(torch.__version__)

1.12.0


In [7]:
x = torch.rand(3)
print(x)

tensor([0.0416, 0.6636, 0.6316])


In [8]:
x = torch.empty(1)

In [9]:
print(x)

tensor([9.1477e-41])


In [10]:
x = torch.empty(1,2,3,4)
print(x)

tensor([[[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]])


In [11]:
y = torch.zeros(1,2)
print(y)

tensor([[0., 0.]])


In [12]:
y = torch.ones(1,3)
print(y)

tensor([[1., 1., 1.]])


In [13]:
z = torch.ones(1,2)
print(z.dtype)

torch.float32


In [14]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)
z = x + y

tensor([[0.6382, 0.8591],
        [0.1933, 0.8140]])
tensor([[0.5204, 0.4401],
        [0.8273, 0.8328]])


In [15]:
print(z)

tensor([[1.1586, 1.2991],
        [1.0206, 1.6468]])


In [16]:
# add
z = torch.add(x,y)
print(z)

tensor([[1.1586, 1.2991],
        [1.0206, 1.6468]])


In [17]:
# sub
z = torch.sub(x,y)
print(z)

tensor([[ 0.1178,  0.4190],
        [-0.6340, -0.0188]])


In [18]:
# multiplication
z = torch.mul(x,y)
print(z)

tensor([[0.3321, 0.3781],
        [0.1599, 0.6779]])


In [19]:
# division
z = torch.div(x,y)
print(z)

tensor([[1.2263, 1.9520],
        [0.2337, 0.9774]])


### Slicing operation

In [20]:
x = torch.rand(3,5)
print(x)

tensor([[0.4414, 0.8574, 0.2245, 0.3247, 0.0185],
        [0.9906, 0.2762, 0.5491, 0.0433, 0.7176],
        [0.4136, 0.0372, 0.6800, 0.9680, 0.7644]])


In [21]:
print(x[1,:])

tensor([0.9906, 0.2762, 0.5491, 0.0433, 0.7176])


In [22]:
print(x[:,1:2])

tensor([[0.8574],
        [0.2762],
        [0.0372]])


In [23]:
print(x[2,3:])

tensor([0.9680, 0.7644])


In [24]:
print(x[2,3])

tensor(0.9680)


In [25]:
print(x[2,3].item()) # By using '.item() method' we will value of tensor and it is valid only for one element.

0.9679996967315674


### Reshaping

In [26]:
x = torch.rand(4,4)
print(x)
y = x.view(16)
print(y)

tensor([[3.3991e-01, 2.4154e-01, 9.5060e-01, 4.7181e-01],
        [3.8694e-01, 6.3179e-01, 3.0065e-01, 3.2124e-01],
        [2.2331e-01, 9.2177e-02, 6.3638e-01, 3.9065e-04],
        [8.1553e-02, 4.3714e-01, 7.1598e-01, 8.3134e-01]])
tensor([3.3991e-01, 2.4154e-01, 9.5060e-01, 4.7181e-01, 3.8694e-01, 6.3179e-01,
        3.0065e-01, 3.2124e-01, 2.2331e-01, 9.2177e-02, 6.3638e-01, 3.9065e-04,
        8.1553e-02, 4.3714e-01, 7.1598e-01, 8.3134e-01])


In [27]:
x = torch.rand(4,4)
print(x)
y = x.view(-1,8)
print(y.size())

tensor([[0.7928, 0.6625, 0.8187, 0.0250],
        [0.1669, 0.5270, 0.3707, 0.6341],
        [0.2017, 0.0147, 0.4508, 0.2466],
        [0.9444, 0.9630, 0.9018, 0.8801]])
torch.Size([2, 8])


### Creating NumPy array

In [28]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [29]:
b= a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [30]:
b= a.numpy()
print(type(b))

<class 'numpy.ndarray'>


In [31]:
a = np.ones(5)
print(a)

[1. 1. 1. 1. 1.]


In [34]:
x = torch.ones(5,requires_grad = True)
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)
